api/urls.py
from .models import CourseResource, CategoryResource
from tastypie.api import Api
from django.urls import path, include

course_resource = CourseResource()
category_resource = CategoryResource()
api = Api(api_name='v1')
api.register(course_resource)
api.register(category_resource)

urlpatterns = [
    path('', include(api.urls), name='index')
]

base/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    #    path('shop/', include('shop.urls')),
    path('', include('shop.urls')),
    path('api/', include('api.urls'))
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:course_id>', views.single_course, name='single_course'),
    path('register', views.register_request, name='register'),
    path('login', views.login_shop, name='login')
]

api/models.py
# from django.db import models
from tastypie.resources import ModelResource
from shop.models import Category, Course
from .authentication import CustomAuthentication
from tastypie.authorization import Authorization


class CategoryResource(ModelResource):
    class Meta:
        queryset = Category.objects.all()
        resource_name = 'categories'
        allowed_methods = ['get']


class CourseResource(ModelResource):
    class Meta:
        queryset = Course.objects.all()
        resource_name = 'cources'
        allowed_methods = ['get', 'post', 'delete']
        excludes = ['created_at', 'reviews_qty']
        authentication = CustomAuthentication()
        authorization = Authorization()

# post hydrate, change data to be incuded in post

    def hydrate(self, bundle):
        bundle.obj.category_id = bundle.data['category_id']
        bundle.obj.reviews_qty = bundle.data['reviews_qty']
        return bundle

# get dehydrate, all resonses from the server

    def dehydrate(self, bundle):
        bundle.data['category_id'] = bundle.obj.category_id
        bundle.data['category'] = bundle.obj.category
        return bundle

    def dehydrate_title(self, bundle):
        return bundle.data['title'].upper()

shop/models.py
from django.db import models
from django.utils import timezone
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

# Create your models here.


class Category(models.Model):
    title = models.CharField(max_length=255)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title


class Course(models.Model):
    title = models.CharField(max_length=300)
    price = models.FloatField()
    students_qty = models.IntegerField()
    reviews_qty = models.IntegerField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title


class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

api/views.py
from django.shortcuts import render

# Create your views here.

shop/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404
from .models import Course, Category, NewUserForm
from django.contrib.auth import login, authenticate
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import admin
# Create your views here.


def index(request):
    courses = Course.objects.all()
    return render(request, 'shop/courses.html', {'courses': courses})


def single_course(request, course_id):
    # Option 1
    # try:
    #     course = Course.objects.get(pk=course_id)
    #     return render(request, 'shop/single_course.html', {'course': course})
    # except Course.DoesNotExist:
    #     raise Http404()

    # Option 2
    course = get_object_or_404(Course, pk=course_id)
    return render(request, 'shop/single_course.html', {'course': course})

# login page


def login_shop(request):
    if request.method == 'POST':

        # AuthenticationForm_can_also_be_used__

        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            form = login(request, user)
            messages.success(request, f' welcome {username} !!')
            return redirect("shop:index")
        else:
            messages.info(request, f'account done not exit plz sign in')
    form = AuthenticationForm()
    return render(request, 'shop/login.html', {'form': form, 'title': 'log in'})

# signup page


def register_request(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful.")
            return redirect("shop:index")
        messages.error(
            request, "Unsuccessful registration. Invalid information.")
    form = NewUserForm()
    return render(request=request, template_name="shop/register.html", context={"register_form": form})

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    <nav class="navbar navbar-dark bg-dark">
        <div class="container">
            <a href={% url "shop:index" %} class="navbar-brand">Courses Shop</a>
            <span class="navbar-text">
                <a href="/admin/" class="me-2" target="_blank">Admin</a>
                <a href="/api/v1/" target="_blank">API</a>
                <a href={% url "shop:register" %} class="m-2">Register</a>
                <a href={% url "shop:login" %}>Login</a>
            </span>
        </div>
    </nav>
    <main class="container">
        {% block content %}
        {% endblock %}
    </main>
</body>

</html>

templates/shop/courses.html
{% extends "base.html" %}

{% block title %}All Courses{% endblock %}

{% block content %}
<table class="table mt-5 table-bordered table-striped table-hover">
    <thead class='table-dark'>
        <tr>
            <th>Title</th>
            <th>Category</th>
            <th>Price</th>
            <th>Students Quantity</th>
            <th></th>
    </thead>
    <tbody>
        {% for course in courses %}
        <tr>
            <td><a href={% url "shop:single_course" course.id %}>{{ course.title }}</a></td>
            <td>{{ course.category }}</td>
            <td>{{ course.price }}</td>
            <td>{{ course.students_qty }}</td>
            <td><button class='btn btn-primary'>buy</button></td>
        </tr>
        {% endfor %}
    </tbody>
    </tr>
</table>
{% endblock %}

templates/shop/login.html
{% extends "base.html" %}

{% block content %}

{% load crispy_forms_tags %}

<div class="content-section col-md-8 col-md-offset-2">
    <center>
        <form method="POST" style="border: 1px solid black; margin: 4%; padding:10%; border-radius:1%;">
            {% csrf_token %}
            <fieldset class="form-group">
                {{ form|crispy}}
            </fieldset>
            <center>
                <button style="background: black; font-size: 2rem; padding:1%;" class="btn btn-outline-info"
                    type="submit"><span class="glyphicon glyphicon-log-in"></span> login</button>
            </center>
            <br />
            <sub style="text-align: left;"><a href={% url "shop:register" %}
                    style="text-decoration: none; color: blue; padding:2%; cursor:pointer; margin-right:2%;">don't have
                    account,sign up</a></sub>
        </form>
    </center>
</div>
{% endblock content %}

templates/shop/register.html
{% extends "base.html" %}

{% block content %}

{% load crispy_forms_tags %}

<!--Register-->
<div class="container py-5">
    <h1>Register</h1>
    <form method="POST">
        {% csrf_token %}
        {{ register_form|crispy }}
        <button class="btn btn-primary" type="submit">Register</button>
    </form>
    <p class="text-center">If you already have an account, <a href="/login">login</a> instead.</p>
</div>

{% endblock %}

templates/shop/single_course.html
{% extends "base.html" %}

{% block title %}{{course.title}}{% endblock %}

{% block content %}

<h1 class="mt-5"> {{ course.title }} is advanced course for those who want full understanding</h1>
<h2> {{ course.title }} is a significant part of {{ course.category }} </h2>
<h3> {{ course.title }} is offered at discount price {{ course.price }} </h3>
<p> The current {{ course.title }} has {{ course.students_qty }} students and more than {{ course.reviews_qty }} reviews <br>
    The course was created on {{ course.created_at }}</p>
<button class="btn btn-primary">Join</button>
{% endblock content %}